// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.34.0
// source: proto/lobby.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LobbyService_CreateLobby_FullMethodName        = "/lobby.LobbyService/CreateLobby"
	LobbyService_InvitePlayers_FullMethodName      = "/lobby.LobbyService/InvitePlayers"
	LobbyService_ConfigureLobby_FullMethodName     = "/lobby.LobbyService/ConfigureLobby"
	LobbyService_LaunchLobby_FullMethodName        = "/lobby.LobbyService/LaunchLobby"
	LobbyService_LeaveLobby_FullMethodName         = "/lobby.LobbyService/LeaveLobby"
	LobbyService_DestroyLobby_FullMethodName       = "/lobby.LobbyService/DestroyLobby"
	LobbyService_GetLobbyState_FullMethodName      = "/lobby.LobbyService/GetLobbyState"
	LobbyService_ShuffleTeams_FullMethodName       = "/lobby.LobbyService/ShuffleTeams"
	LobbyService_FlipTeams_FullMethodName          = "/lobby.LobbyService/FlipTeams"
	LobbyService_KickPlayer_FullMethodName         = "/lobby.LobbyService/KickPlayer"
	LobbyService_StreamLobbyUpdates_FullMethodName = "/lobby.LobbyService/StreamLobbyUpdates"
	LobbyService_GetBotStatus_FullMethodName       = "/lobby.LobbyService/GetBotStatus"
)

// LobbyServiceClient is the client API for LobbyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LobbyServiceClient interface {
	// CreateLobby creates a new Dota 2 practice lobby
	CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyResponse, error)
	// InvitePlayers invites players to the current lobby
	InvitePlayers(ctx context.Context, in *InvitePlayersRequest, opts ...grpc.CallOption) (*InvitePlayersResponse, error)
	// ConfigureLobby updates lobby settings
	ConfigureLobby(ctx context.Context, in *ConfigureLobbyRequest, opts ...grpc.CallOption) (*ConfigureLobbyResponse, error)
	// LaunchLobby starts the game
	LaunchLobby(ctx context.Context, in *LaunchLobbyRequest, opts ...grpc.CallOption) (*LaunchLobbyResponse, error)
	// LeaveLobby leaves the current lobby
	LeaveLobby(ctx context.Context, in *LeaveLobbyRequest, opts ...grpc.CallOption) (*LeaveLobbyResponse, error)
	// DestroyLobby destroys the current lobby
	DestroyLobby(ctx context.Context, in *DestroyLobbyRequest, opts ...grpc.CallOption) (*DestroyLobbyResponse, error)
	// GetLobbyState returns the current lobby state
	GetLobbyState(ctx context.Context, in *GetLobbyStateRequest, opts ...grpc.CallOption) (*LobbyState, error)
	// ShuffleTeams performs balanced shuffle
	ShuffleTeams(ctx context.Context, in *ShuffleTeamsRequest, opts ...grpc.CallOption) (*ShuffleTeamsResponse, error)
	// FlipTeams swaps radiant and dire
	FlipTeams(ctx context.Context, in *FlipTeamsRequest, opts ...grpc.CallOption) (*FlipTeamsResponse, error)
	// KickPlayer kicks a player from the lobby
	KickPlayer(ctx context.Context, in *KickPlayerRequest, opts ...grpc.CallOption) (*KickPlayerResponse, error)
	// StreamLobbyUpdates streams real-time lobby updates
	StreamLobbyUpdates(ctx context.Context, in *StreamLobbyUpdatesRequest, opts ...grpc.CallOption) (LobbyService_StreamLobbyUpdatesClient, error)
	// GetBotStatus returns the bot's connection status
	GetBotStatus(ctx context.Context, in *GetBotStatusRequest, opts ...grpc.CallOption) (*BotStatus, error)
}

type lobbyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLobbyServiceClient(cc grpc.ClientConnInterface) LobbyServiceClient {
	return &lobbyServiceClient{cc}
}

func (c *lobbyServiceClient) CreateLobby(ctx context.Context, in *CreateLobbyRequest, opts ...grpc.CallOption) (*CreateLobbyResponse, error) {
	out := new(CreateLobbyResponse)
	err := c.cc.Invoke(ctx, LobbyService_CreateLobby_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) InvitePlayers(ctx context.Context, in *InvitePlayersRequest, opts ...grpc.CallOption) (*InvitePlayersResponse, error) {
	out := new(InvitePlayersResponse)
	err := c.cc.Invoke(ctx, LobbyService_InvitePlayers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) ConfigureLobby(ctx context.Context, in *ConfigureLobbyRequest, opts ...grpc.CallOption) (*ConfigureLobbyResponse, error) {
	out := new(ConfigureLobbyResponse)
	err := c.cc.Invoke(ctx, LobbyService_ConfigureLobby_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) LaunchLobby(ctx context.Context, in *LaunchLobbyRequest, opts ...grpc.CallOption) (*LaunchLobbyResponse, error) {
	out := new(LaunchLobbyResponse)
	err := c.cc.Invoke(ctx, LobbyService_LaunchLobby_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) LeaveLobby(ctx context.Context, in *LeaveLobbyRequest, opts ...grpc.CallOption) (*LeaveLobbyResponse, error) {
	out := new(LeaveLobbyResponse)
	err := c.cc.Invoke(ctx, LobbyService_LeaveLobby_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) DestroyLobby(ctx context.Context, in *DestroyLobbyRequest, opts ...grpc.CallOption) (*DestroyLobbyResponse, error) {
	out := new(DestroyLobbyResponse)
	err := c.cc.Invoke(ctx, LobbyService_DestroyLobby_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) GetLobbyState(ctx context.Context, in *GetLobbyStateRequest, opts ...grpc.CallOption) (*LobbyState, error) {
	out := new(LobbyState)
	err := c.cc.Invoke(ctx, LobbyService_GetLobbyState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) ShuffleTeams(ctx context.Context, in *ShuffleTeamsRequest, opts ...grpc.CallOption) (*ShuffleTeamsResponse, error) {
	out := new(ShuffleTeamsResponse)
	err := c.cc.Invoke(ctx, LobbyService_ShuffleTeams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) FlipTeams(ctx context.Context, in *FlipTeamsRequest, opts ...grpc.CallOption) (*FlipTeamsResponse, error) {
	out := new(FlipTeamsResponse)
	err := c.cc.Invoke(ctx, LobbyService_FlipTeams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) KickPlayer(ctx context.Context, in *KickPlayerRequest, opts ...grpc.CallOption) (*KickPlayerResponse, error) {
	out := new(KickPlayerResponse)
	err := c.cc.Invoke(ctx, LobbyService_KickPlayer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lobbyServiceClient) StreamLobbyUpdates(ctx context.Context, in *StreamLobbyUpdatesRequest, opts ...grpc.CallOption) (LobbyService_StreamLobbyUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &LobbyService_ServiceDesc.Streams[0], LobbyService_StreamLobbyUpdates_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lobbyServiceStreamLobbyUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LobbyService_StreamLobbyUpdatesClient interface {
	Recv() (*LobbyUpdate, error)
	grpc.ClientStream
}

type lobbyServiceStreamLobbyUpdatesClient struct {
	grpc.ClientStream
}

func (x *lobbyServiceStreamLobbyUpdatesClient) Recv() (*LobbyUpdate, error) {
	m := new(LobbyUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lobbyServiceClient) GetBotStatus(ctx context.Context, in *GetBotStatusRequest, opts ...grpc.CallOption) (*BotStatus, error) {
	out := new(BotStatus)
	err := c.cc.Invoke(ctx, LobbyService_GetBotStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LobbyServiceServer is the server API for LobbyService service.
// All implementations must embed UnimplementedLobbyServiceServer
// for forward compatibility
type LobbyServiceServer interface {
	// CreateLobby creates a new Dota 2 practice lobby
	CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyResponse, error)
	// InvitePlayers invites players to the current lobby
	InvitePlayers(context.Context, *InvitePlayersRequest) (*InvitePlayersResponse, error)
	// ConfigureLobby updates lobby settings
	ConfigureLobby(context.Context, *ConfigureLobbyRequest) (*ConfigureLobbyResponse, error)
	// LaunchLobby starts the game
	LaunchLobby(context.Context, *LaunchLobbyRequest) (*LaunchLobbyResponse, error)
	// LeaveLobby leaves the current lobby
	LeaveLobby(context.Context, *LeaveLobbyRequest) (*LeaveLobbyResponse, error)
	// DestroyLobby destroys the current lobby
	DestroyLobby(context.Context, *DestroyLobbyRequest) (*DestroyLobbyResponse, error)
	// GetLobbyState returns the current lobby state
	GetLobbyState(context.Context, *GetLobbyStateRequest) (*LobbyState, error)
	// ShuffleTeams performs balanced shuffle
	ShuffleTeams(context.Context, *ShuffleTeamsRequest) (*ShuffleTeamsResponse, error)
	// FlipTeams swaps radiant and dire
	FlipTeams(context.Context, *FlipTeamsRequest) (*FlipTeamsResponse, error)
	// KickPlayer kicks a player from the lobby
	KickPlayer(context.Context, *KickPlayerRequest) (*KickPlayerResponse, error)
	// StreamLobbyUpdates streams real-time lobby updates
	StreamLobbyUpdates(*StreamLobbyUpdatesRequest, LobbyService_StreamLobbyUpdatesServer) error
	// GetBotStatus returns the bot's connection status
	GetBotStatus(context.Context, *GetBotStatusRequest) (*BotStatus, error)
	mustEmbedUnimplementedLobbyServiceServer()
}

// UnimplementedLobbyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLobbyServiceServer struct {
}

func (UnimplementedLobbyServiceServer) CreateLobby(context.Context, *CreateLobbyRequest) (*CreateLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLobby not implemented")
}
func (UnimplementedLobbyServiceServer) InvitePlayers(context.Context, *InvitePlayersRequest) (*InvitePlayersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvitePlayers not implemented")
}
func (UnimplementedLobbyServiceServer) ConfigureLobby(context.Context, *ConfigureLobbyRequest) (*ConfigureLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureLobby not implemented")
}
func (UnimplementedLobbyServiceServer) LaunchLobby(context.Context, *LaunchLobbyRequest) (*LaunchLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchLobby not implemented")
}
func (UnimplementedLobbyServiceServer) LeaveLobby(context.Context, *LeaveLobbyRequest) (*LeaveLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveLobby not implemented")
}
func (UnimplementedLobbyServiceServer) DestroyLobby(context.Context, *DestroyLobbyRequest) (*DestroyLobbyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyLobby not implemented")
}
func (UnimplementedLobbyServiceServer) GetLobbyState(context.Context, *GetLobbyStateRequest) (*LobbyState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLobbyState not implemented")
}
func (UnimplementedLobbyServiceServer) ShuffleTeams(context.Context, *ShuffleTeamsRequest) (*ShuffleTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShuffleTeams not implemented")
}
func (UnimplementedLobbyServiceServer) FlipTeams(context.Context, *FlipTeamsRequest) (*FlipTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlipTeams not implemented")
}
func (UnimplementedLobbyServiceServer) KickPlayer(context.Context, *KickPlayerRequest) (*KickPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickPlayer not implemented")
}
func (UnimplementedLobbyServiceServer) StreamLobbyUpdates(*StreamLobbyUpdatesRequest, LobbyService_StreamLobbyUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLobbyUpdates not implemented")
}
func (UnimplementedLobbyServiceServer) GetBotStatus(context.Context, *GetBotStatusRequest) (*BotStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBotStatus not implemented")
}
func (UnimplementedLobbyServiceServer) mustEmbedUnimplementedLobbyServiceServer() {}

// UnsafeLobbyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LobbyServiceServer will
// result in compilation errors.
type UnsafeLobbyServiceServer interface {
	mustEmbedUnimplementedLobbyServiceServer()
}

func RegisterLobbyServiceServer(s grpc.ServiceRegistrar, srv LobbyServiceServer) {
	s.RegisterService(&LobbyService_ServiceDesc, srv)
}

func _LobbyService_CreateLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).CreateLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_CreateLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).CreateLobby(ctx, req.(*CreateLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_InvitePlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvitePlayersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).InvitePlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_InvitePlayers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).InvitePlayers(ctx, req.(*InvitePlayersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_ConfigureLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).ConfigureLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_ConfigureLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).ConfigureLobby(ctx, req.(*ConfigureLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_LaunchLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).LaunchLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_LaunchLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).LaunchLobby(ctx, req.(*LaunchLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_LeaveLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).LeaveLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_LeaveLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).LeaveLobby(ctx, req.(*LeaveLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_DestroyLobby_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyLobbyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).DestroyLobby(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_DestroyLobby_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).DestroyLobby(ctx, req.(*DestroyLobbyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_GetLobbyState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLobbyStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).GetLobbyState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_GetLobbyState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).GetLobbyState(ctx, req.(*GetLobbyStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_ShuffleTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShuffleTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).ShuffleTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_ShuffleTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).ShuffleTeams(ctx, req.(*ShuffleTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_FlipTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlipTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).FlipTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_FlipTeams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).FlipTeams(ctx, req.(*FlipTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_KickPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).KickPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_KickPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).KickPlayer(ctx, req.(*KickPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LobbyService_StreamLobbyUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLobbyUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LobbyServiceServer).StreamLobbyUpdates(m, &lobbyServiceStreamLobbyUpdatesServer{stream})
}

type LobbyService_StreamLobbyUpdatesServer interface {
	Send(*LobbyUpdate) error
	grpc.ServerStream
}

type lobbyServiceStreamLobbyUpdatesServer struct {
	grpc.ServerStream
}

func (x *lobbyServiceStreamLobbyUpdatesServer) Send(m *LobbyUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _LobbyService_GetBotStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LobbyServiceServer).GetBotStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LobbyService_GetBotStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LobbyServiceServer).GetBotStatus(ctx, req.(*GetBotStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LobbyService_ServiceDesc is the grpc.ServiceDesc for LobbyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LobbyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lobby.LobbyService",
	HandlerType: (*LobbyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLobby",
			Handler:    _LobbyService_CreateLobby_Handler,
		},
		{
			MethodName: "InvitePlayers",
			Handler:    _LobbyService_InvitePlayers_Handler,
		},
		{
			MethodName: "ConfigureLobby",
			Handler:    _LobbyService_ConfigureLobby_Handler,
		},
		{
			MethodName: "LaunchLobby",
			Handler:    _LobbyService_LaunchLobby_Handler,
		},
		{
			MethodName: "LeaveLobby",
			Handler:    _LobbyService_LeaveLobby_Handler,
		},
		{
			MethodName: "DestroyLobby",
			Handler:    _LobbyService_DestroyLobby_Handler,
		},
		{
			MethodName: "GetLobbyState",
			Handler:    _LobbyService_GetLobbyState_Handler,
		},
		{
			MethodName: "ShuffleTeams",
			Handler:    _LobbyService_ShuffleTeams_Handler,
		},
		{
			MethodName: "FlipTeams",
			Handler:    _LobbyService_FlipTeams_Handler,
		},
		{
			MethodName: "KickPlayer",
			Handler:    _LobbyService_KickPlayer_Handler,
		},
		{
			MethodName: "GetBotStatus",
			Handler:    _LobbyService_GetBotStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLobbyUpdates",
			Handler:       _LobbyService_StreamLobbyUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/lobby.proto",
}
