// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/lobby.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LobbyStatus int32

const (
	LobbyStatus_LOBBY_STATUS_UNKNOWN   LobbyStatus = 0
	LobbyStatus_LOBBY_STATUS_CREATED   LobbyStatus = 1
	LobbyStatus_LOBBY_STATUS_WAITING   LobbyStatus = 2
	LobbyStatus_LOBBY_STATUS_READY     LobbyStatus = 3
	LobbyStatus_LOBBY_STATUS_IN_GAME   LobbyStatus = 4
	LobbyStatus_LOBBY_STATUS_POST_GAME LobbyStatus = 5
)

// Enum value maps for LobbyStatus.
var (
	LobbyStatus_name = map[int32]string{
		0: "LOBBY_STATUS_UNKNOWN",
		1: "LOBBY_STATUS_CREATED",
		2: "LOBBY_STATUS_WAITING",
		3: "LOBBY_STATUS_READY",
		4: "LOBBY_STATUS_IN_GAME",
		5: "LOBBY_STATUS_POST_GAME",
	}
	LobbyStatus_value = map[string]int32{
		"LOBBY_STATUS_UNKNOWN":   0,
		"LOBBY_STATUS_CREATED":   1,
		"LOBBY_STATUS_WAITING":   2,
		"LOBBY_STATUS_READY":     3,
		"LOBBY_STATUS_IN_GAME":   4,
		"LOBBY_STATUS_POST_GAME": 5,
	}
)

func (x LobbyStatus) Enum() *LobbyStatus {
	p := new(LobbyStatus)
	*p = x
	return p
}

func (x LobbyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lobby_proto_enumTypes[0].Descriptor()
}

func (LobbyStatus) Type() protoreflect.EnumType {
	return &file_proto_lobby_proto_enumTypes[0]
}

func (x LobbyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyStatus.Descriptor instead.
func (LobbyStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{0}
}

type LobbyTeam int32

const (
	LobbyTeam_TEAM_UNASSIGNED  LobbyTeam = 0
	LobbyTeam_TEAM_RADIANT     LobbyTeam = 1
	LobbyTeam_TEAM_DIRE        LobbyTeam = 2
	LobbyTeam_TEAM_SPECTATOR   LobbyTeam = 3
	LobbyTeam_TEAM_BROADCASTER LobbyTeam = 4
)

// Enum value maps for LobbyTeam.
var (
	LobbyTeam_name = map[int32]string{
		0: "TEAM_UNASSIGNED",
		1: "TEAM_RADIANT",
		2: "TEAM_DIRE",
		3: "TEAM_SPECTATOR",
		4: "TEAM_BROADCASTER",
	}
	LobbyTeam_value = map[string]int32{
		"TEAM_UNASSIGNED":  0,
		"TEAM_RADIANT":     1,
		"TEAM_DIRE":        2,
		"TEAM_SPECTATOR":   3,
		"TEAM_BROADCASTER": 4,
	}
)

func (x LobbyTeam) Enum() *LobbyTeam {
	p := new(LobbyTeam)
	*p = x
	return p
}

func (x LobbyTeam) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyTeam) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lobby_proto_enumTypes[1].Descriptor()
}

func (LobbyTeam) Type() protoreflect.EnumType {
	return &file_proto_lobby_proto_enumTypes[1]
}

func (x LobbyTeam) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyTeam.Descriptor instead.
func (LobbyTeam) EnumDescriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{1}
}

type LobbyUpdateType int32

const (
	LobbyUpdateType_UPDATE_TYPE_UNKNOWN        LobbyUpdateType = 0
	LobbyUpdateType_UPDATE_TYPE_CREATED        LobbyUpdateType = 1
	LobbyUpdateType_UPDATE_TYPE_CONFIG_CHANGED LobbyUpdateType = 2
	LobbyUpdateType_UPDATE_TYPE_PLAYER_JOINED  LobbyUpdateType = 3
	LobbyUpdateType_UPDATE_TYPE_PLAYER_LEFT    LobbyUpdateType = 4
	LobbyUpdateType_UPDATE_TYPE_TEAM_CHANGED   LobbyUpdateType = 5
	LobbyUpdateType_UPDATE_TYPE_LAUNCHED       LobbyUpdateType = 6
	LobbyUpdateType_UPDATE_TYPE_FINISHED       LobbyUpdateType = 7
	LobbyUpdateType_UPDATE_TYPE_DESTROYED      LobbyUpdateType = 8
)

// Enum value maps for LobbyUpdateType.
var (
	LobbyUpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNKNOWN",
		1: "UPDATE_TYPE_CREATED",
		2: "UPDATE_TYPE_CONFIG_CHANGED",
		3: "UPDATE_TYPE_PLAYER_JOINED",
		4: "UPDATE_TYPE_PLAYER_LEFT",
		5: "UPDATE_TYPE_TEAM_CHANGED",
		6: "UPDATE_TYPE_LAUNCHED",
		7: "UPDATE_TYPE_FINISHED",
		8: "UPDATE_TYPE_DESTROYED",
	}
	LobbyUpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNKNOWN":        0,
		"UPDATE_TYPE_CREATED":        1,
		"UPDATE_TYPE_CONFIG_CHANGED": 2,
		"UPDATE_TYPE_PLAYER_JOINED":  3,
		"UPDATE_TYPE_PLAYER_LEFT":    4,
		"UPDATE_TYPE_TEAM_CHANGED":   5,
		"UPDATE_TYPE_LAUNCHED":       6,
		"UPDATE_TYPE_FINISHED":       7,
		"UPDATE_TYPE_DESTROYED":      8,
	}
)

func (x LobbyUpdateType) Enum() *LobbyUpdateType {
	p := new(LobbyUpdateType)
	*p = x
	return p
}

func (x LobbyUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LobbyUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lobby_proto_enumTypes[2].Descriptor()
}

func (LobbyUpdateType) Type() protoreflect.EnumType {
	return &file_proto_lobby_proto_enumTypes[2]
}

func (x LobbyUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LobbyUpdateType.Descriptor instead.
func (LobbyUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{2}
}

// Server region constants
type ServerRegion int32

const (
	ServerRegion_REGION_UNSPECIFIED  ServerRegion = 0
	ServerRegion_REGION_US_WEST      ServerRegion = 1
	ServerRegion_REGION_US_EAST      ServerRegion = 2
	ServerRegion_REGION_EUROPE       ServerRegion = 3
	ServerRegion_REGION_KOREA        ServerRegion = 4
	ServerRegion_REGION_SINGAPORE    ServerRegion = 5
	ServerRegion_REGION_DUBAI        ServerRegion = 6
	ServerRegion_REGION_AUSTRALIA    ServerRegion = 7
	ServerRegion_REGION_STOCKHOLM    ServerRegion = 8
	ServerRegion_REGION_AUSTRIA      ServerRegion = 9
	ServerRegion_REGION_BRAZIL       ServerRegion = 10
	ServerRegion_REGION_SOUTH_AFRICA ServerRegion = 11
	ServerRegion_REGION_CHILE        ServerRegion = 14
	ServerRegion_REGION_PERU         ServerRegion = 15
	ServerRegion_REGION_INDIA        ServerRegion = 16
	ServerRegion_REGION_JAPAN        ServerRegion = 19
)

// Enum value maps for ServerRegion.
var (
	ServerRegion_name = map[int32]string{
		0:  "REGION_UNSPECIFIED",
		1:  "REGION_US_WEST",
		2:  "REGION_US_EAST",
		3:  "REGION_EUROPE",
		4:  "REGION_KOREA",
		5:  "REGION_SINGAPORE",
		6:  "REGION_DUBAI",
		7:  "REGION_AUSTRALIA",
		8:  "REGION_STOCKHOLM",
		9:  "REGION_AUSTRIA",
		10: "REGION_BRAZIL",
		11: "REGION_SOUTH_AFRICA",
		14: "REGION_CHILE",
		15: "REGION_PERU",
		16: "REGION_INDIA",
		19: "REGION_JAPAN",
	}
	ServerRegion_value = map[string]int32{
		"REGION_UNSPECIFIED":  0,
		"REGION_US_WEST":      1,
		"REGION_US_EAST":      2,
		"REGION_EUROPE":       3,
		"REGION_KOREA":        4,
		"REGION_SINGAPORE":    5,
		"REGION_DUBAI":        6,
		"REGION_AUSTRALIA":    7,
		"REGION_STOCKHOLM":    8,
		"REGION_AUSTRIA":      9,
		"REGION_BRAZIL":       10,
		"REGION_SOUTH_AFRICA": 11,
		"REGION_CHILE":        14,
		"REGION_PERU":         15,
		"REGION_INDIA":        16,
		"REGION_JAPAN":        19,
	}
)

func (x ServerRegion) Enum() *ServerRegion {
	p := new(ServerRegion)
	*p = x
	return p
}

func (x ServerRegion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerRegion) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lobby_proto_enumTypes[3].Descriptor()
}

func (ServerRegion) Type() protoreflect.EnumType {
	return &file_proto_lobby_proto_enumTypes[3]
}

func (x ServerRegion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerRegion.Descriptor instead.
func (ServerRegion) EnumDescriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{3}
}

// Game mode constants
type GameMode int32

const (
	GameMode_GAME_MODE_UNKNOWN       GameMode = 0
	GameMode_GAME_MODE_ALL_PICK      GameMode = 1
	GameMode_GAME_MODE_CAPTAINS_MODE GameMode = 2
	GameMode_GAME_MODE_RANDOM_DRAFT  GameMode = 3
	GameMode_GAME_MODE_SINGLE_DRAFT  GameMode = 4
	GameMode_GAME_MODE_ALL_RANDOM    GameMode = 5
)

// Enum value maps for GameMode.
var (
	GameMode_name = map[int32]string{
		0: "GAME_MODE_UNKNOWN",
		1: "GAME_MODE_ALL_PICK",
		2: "GAME_MODE_CAPTAINS_MODE",
		3: "GAME_MODE_RANDOM_DRAFT",
		4: "GAME_MODE_SINGLE_DRAFT",
		5: "GAME_MODE_ALL_RANDOM",
	}
	GameMode_value = map[string]int32{
		"GAME_MODE_UNKNOWN":       0,
		"GAME_MODE_ALL_PICK":      1,
		"GAME_MODE_CAPTAINS_MODE": 2,
		"GAME_MODE_RANDOM_DRAFT":  3,
		"GAME_MODE_SINGLE_DRAFT":  4,
		"GAME_MODE_ALL_RANDOM":    5,
	}
)

func (x GameMode) Enum() *GameMode {
	p := new(GameMode)
	*p = x
	return p
}

func (x GameMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lobby_proto_enumTypes[4].Descriptor()
}

func (GameMode) Type() protoreflect.EnumType {
	return &file_proto_lobby_proto_enumTypes[4]
}

func (x GameMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameMode.Descriptor instead.
func (GameMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{4}
}

// CreateLobbyRequest contains parameters for creating a lobby
type CreateLobbyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ServerRegion    uint32                 `protobuf:"varint,3,opt,name=server_region,json=serverRegion,proto3" json:"server_region,omitempty"` // See ServerRegion enum
	GameMode        uint32                 `protobuf:"varint,4,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`             // See GameMode enum
	AllowCheats     bool                   `protobuf:"varint,5,opt,name=allow_cheats,json=allowCheats,proto3" json:"allow_cheats,omitempty"`
	AllowSpectators bool                   `protobuf:"varint,6,opt,name=allow_spectators,json=allowSpectators,proto3" json:"allow_spectators,omitempty"`
	InviteSteamIds  []uint64               `protobuf:"varint,7,rep,packed,name=invite_steam_ids,json=inviteSteamIds,proto3" json:"invite_steam_ids,omitempty"` // Players to invite immediately
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateLobbyRequest) Reset() {
	*x = CreateLobbyRequest{}
	mi := &file_proto_lobby_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyRequest) ProtoMessage() {}

func (x *CreateLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyRequest.ProtoReflect.Descriptor instead.
func (*CreateLobbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLobbyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLobbyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateLobbyRequest) GetServerRegion() uint32 {
	if x != nil {
		return x.ServerRegion
	}
	return 0
}

func (x *CreateLobbyRequest) GetGameMode() uint32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *CreateLobbyRequest) GetAllowCheats() bool {
	if x != nil {
		return x.AllowCheats
	}
	return false
}

func (x *CreateLobbyRequest) GetAllowSpectators() bool {
	if x != nil {
		return x.AllowSpectators
	}
	return false
}

func (x *CreateLobbyRequest) GetInviteSteamIds() []uint64 {
	if x != nil {
		return x.InviteSteamIds
	}
	return nil
}

type CreateLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	LobbyId       uint64                 `protobuf:"varint,3,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLobbyResponse) Reset() {
	*x = CreateLobbyResponse{}
	mi := &file_proto_lobby_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLobbyResponse) ProtoMessage() {}

func (x *CreateLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLobbyResponse.ProtoReflect.Descriptor instead.
func (*CreateLobbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLobbyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateLobbyResponse) GetLobbyId() uint64 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *CreateLobbyResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InvitePlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamIds      []uint64               `protobuf:"varint,1,rep,packed,name=steam_ids,json=steamIds,proto3" json:"steam_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitePlayersRequest) Reset() {
	*x = InvitePlayersRequest{}
	mi := &file_proto_lobby_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitePlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitePlayersRequest) ProtoMessage() {}

func (x *InvitePlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitePlayersRequest.ProtoReflect.Descriptor instead.
func (*InvitePlayersRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{2}
}

func (x *InvitePlayersRequest) GetSteamIds() []uint64 {
	if x != nil {
		return x.SteamIds
	}
	return nil
}

type InvitePlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	InviteResults map[uint64]bool        `protobuf:"bytes,3,rep,name=invite_results,json=inviteResults,proto3" json:"invite_results,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // steam_id -> success
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitePlayersResponse) Reset() {
	*x = InvitePlayersResponse{}
	mi := &file_proto_lobby_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitePlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitePlayersResponse) ProtoMessage() {}

func (x *InvitePlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitePlayersResponse.ProtoReflect.Descriptor instead.
func (*InvitePlayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{3}
}

func (x *InvitePlayersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvitePlayersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InvitePlayersResponse) GetInviteResults() map[uint64]bool {
	if x != nil {
		return x.InviteResults
	}
	return nil
}

type ConfigureLobbyRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ServerRegion    uint32                 `protobuf:"varint,3,opt,name=server_region,json=serverRegion,proto3" json:"server_region,omitempty"`
	GameMode        uint32                 `protobuf:"varint,4,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	AllowCheats     bool                   `protobuf:"varint,5,opt,name=allow_cheats,json=allowCheats,proto3" json:"allow_cheats,omitempty"`
	AllowSpectators bool                   `protobuf:"varint,6,opt,name=allow_spectators,json=allowSpectators,proto3" json:"allow_spectators,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigureLobbyRequest) Reset() {
	*x = ConfigureLobbyRequest{}
	mi := &file_proto_lobby_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureLobbyRequest) ProtoMessage() {}

func (x *ConfigureLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureLobbyRequest.ProtoReflect.Descriptor instead.
func (*ConfigureLobbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureLobbyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigureLobbyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConfigureLobbyRequest) GetServerRegion() uint32 {
	if x != nil {
		return x.ServerRegion
	}
	return 0
}

func (x *ConfigureLobbyRequest) GetGameMode() uint32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *ConfigureLobbyRequest) GetAllowCheats() bool {
	if x != nil {
		return x.AllowCheats
	}
	return false
}

func (x *ConfigureLobbyRequest) GetAllowSpectators() bool {
	if x != nil {
		return x.AllowSpectators
	}
	return false
}

type ConfigureLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureLobbyResponse) Reset() {
	*x = ConfigureLobbyResponse{}
	mi := &file_proto_lobby_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureLobbyResponse) ProtoMessage() {}

func (x *ConfigureLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureLobbyResponse.ProtoReflect.Descriptor instead.
func (*ConfigureLobbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigureLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureLobbyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LaunchLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchLobbyRequest) Reset() {
	*x = LaunchLobbyRequest{}
	mi := &file_proto_lobby_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchLobbyRequest) ProtoMessage() {}

func (x *LaunchLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchLobbyRequest.ProtoReflect.Descriptor instead.
func (*LaunchLobbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{6}
}

type LaunchLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	MatchId       uint64                 `protobuf:"varint,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // Match ID once game starts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchLobbyResponse) Reset() {
	*x = LaunchLobbyResponse{}
	mi := &file_proto_lobby_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchLobbyResponse) ProtoMessage() {}

func (x *LaunchLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchLobbyResponse.ProtoReflect.Descriptor instead.
func (*LaunchLobbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{7}
}

func (x *LaunchLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LaunchLobbyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LaunchLobbyResponse) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

type LeaveLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyRequest) Reset() {
	*x = LeaveLobbyRequest{}
	mi := &file_proto_lobby_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyRequest) ProtoMessage() {}

func (x *LeaveLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyRequest.ProtoReflect.Descriptor instead.
func (*LeaveLobbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{8}
}

type LeaveLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveLobbyResponse) Reset() {
	*x = LeaveLobbyResponse{}
	mi := &file_proto_lobby_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveLobbyResponse) ProtoMessage() {}

func (x *LeaveLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveLobbyResponse.ProtoReflect.Descriptor instead.
func (*LeaveLobbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveLobbyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DestroyLobbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyLobbyRequest) Reset() {
	*x = DestroyLobbyRequest{}
	mi := &file_proto_lobby_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyLobbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyLobbyRequest) ProtoMessage() {}

func (x *DestroyLobbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyLobbyRequest.ProtoReflect.Descriptor instead.
func (*DestroyLobbyRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{10}
}

type DestroyLobbyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyLobbyResponse) Reset() {
	*x = DestroyLobbyResponse{}
	mi := &file_proto_lobby_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyLobbyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyLobbyResponse) ProtoMessage() {}

func (x *DestroyLobbyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyLobbyResponse.ProtoReflect.Descriptor instead.
func (*DestroyLobbyResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{11}
}

func (x *DestroyLobbyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyLobbyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetLobbyStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLobbyStateRequest) Reset() {
	*x = GetLobbyStateRequest{}
	mi := &file_proto_lobby_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLobbyStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLobbyStateRequest) ProtoMessage() {}

func (x *GetLobbyStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLobbyStateRequest.ProtoReflect.Descriptor instead.
func (*GetLobbyStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{12}
}

type LobbyState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InLobby       bool                   `protobuf:"varint,1,opt,name=in_lobby,json=inLobby,proto3" json:"in_lobby,omitempty"`
	LobbyId       uint64                 `protobuf:"varint,2,opt,name=lobby_id,json=lobbyId,proto3" json:"lobby_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Status        LobbyStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=lobby.LobbyStatus" json:"status,omitempty"`
	ServerRegion  uint32                 `protobuf:"varint,6,opt,name=server_region,json=serverRegion,proto3" json:"server_region,omitempty"`
	GameMode      uint32                 `protobuf:"varint,7,opt,name=game_mode,json=gameMode,proto3" json:"game_mode,omitempty"`
	MatchId       uint64                 `protobuf:"varint,8,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Members       []*LobbyMember         `protobuf:"bytes,9,rep,name=members,proto3" json:"members,omitempty"`
	RadiantCount  int32                  `protobuf:"varint,10,opt,name=radiant_count,json=radiantCount,proto3" json:"radiant_count,omitempty"`
	DireCount     int32                  `protobuf:"varint,11,opt,name=dire_count,json=direCount,proto3" json:"dire_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyState) Reset() {
	*x = LobbyState{}
	mi := &file_proto_lobby_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyState) ProtoMessage() {}

func (x *LobbyState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyState.ProtoReflect.Descriptor instead.
func (*LobbyState) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{13}
}

func (x *LobbyState) GetInLobby() bool {
	if x != nil {
		return x.InLobby
	}
	return false
}

func (x *LobbyState) GetLobbyId() uint64 {
	if x != nil {
		return x.LobbyId
	}
	return 0
}

func (x *LobbyState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyState) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LobbyState) GetStatus() LobbyStatus {
	if x != nil {
		return x.Status
	}
	return LobbyStatus_LOBBY_STATUS_UNKNOWN
}

func (x *LobbyState) GetServerRegion() uint32 {
	if x != nil {
		return x.ServerRegion
	}
	return 0
}

func (x *LobbyState) GetGameMode() uint32 {
	if x != nil {
		return x.GameMode
	}
	return 0
}

func (x *LobbyState) GetMatchId() uint64 {
	if x != nil {
		return x.MatchId
	}
	return 0
}

func (x *LobbyState) GetMembers() []*LobbyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *LobbyState) GetRadiantCount() int32 {
	if x != nil {
		return x.RadiantCount
	}
	return 0
}

func (x *LobbyState) GetDireCount() int32 {
	if x != nil {
		return x.DireCount
	}
	return 0
}

type LobbyMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SteamId       uint64                 `protobuf:"varint,1,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	AccountId     uint32                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Team          LobbyTeam              `protobuf:"varint,4,opt,name=team,proto3,enum=lobby.LobbyTeam" json:"team,omitempty"`
	Slot          uint32                 `protobuf:"varint,5,opt,name=slot,proto3" json:"slot,omitempty"`
	IsReady       bool                   `protobuf:"varint,6,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	IsHost        bool                   `protobuf:"varint,7,opt,name=is_host,json=isHost,proto3" json:"is_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyMember) Reset() {
	*x = LobbyMember{}
	mi := &file_proto_lobby_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyMember) ProtoMessage() {}

func (x *LobbyMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyMember.ProtoReflect.Descriptor instead.
func (*LobbyMember) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{14}
}

func (x *LobbyMember) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *LobbyMember) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LobbyMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LobbyMember) GetTeam() LobbyTeam {
	if x != nil {
		return x.Team
	}
	return LobbyTeam_TEAM_UNASSIGNED
}

func (x *LobbyMember) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *LobbyMember) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *LobbyMember) GetIsHost() bool {
	if x != nil {
		return x.IsHost
	}
	return false
}

type ShuffleTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleTeamsRequest) Reset() {
	*x = ShuffleTeamsRequest{}
	mi := &file_proto_lobby_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleTeamsRequest) ProtoMessage() {}

func (x *ShuffleTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleTeamsRequest.ProtoReflect.Descriptor instead.
func (*ShuffleTeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{15}
}

type ShuffleTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleTeamsResponse) Reset() {
	*x = ShuffleTeamsResponse{}
	mi := &file_proto_lobby_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleTeamsResponse) ProtoMessage() {}

func (x *ShuffleTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleTeamsResponse.ProtoReflect.Descriptor instead.
func (*ShuffleTeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{16}
}

func (x *ShuffleTeamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShuffleTeamsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FlipTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlipTeamsRequest) Reset() {
	*x = FlipTeamsRequest{}
	mi := &file_proto_lobby_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlipTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlipTeamsRequest) ProtoMessage() {}

func (x *FlipTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlipTeamsRequest.ProtoReflect.Descriptor instead.
func (*FlipTeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{17}
}

type FlipTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlipTeamsResponse) Reset() {
	*x = FlipTeamsResponse{}
	mi := &file_proto_lobby_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlipTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlipTeamsResponse) ProtoMessage() {}

func (x *FlipTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlipTeamsResponse.ProtoReflect.Descriptor instead.
func (*FlipTeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{18}
}

func (x *FlipTeamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FlipTeamsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KickPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint32                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerRequest) Reset() {
	*x = KickPlayerRequest{}
	mi := &file_proto_lobby_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerRequest) ProtoMessage() {}

func (x *KickPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerRequest.ProtoReflect.Descriptor instead.
func (*KickPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{19}
}

func (x *KickPlayerRequest) GetAccountId() uint32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type KickPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickPlayerResponse) Reset() {
	*x = KickPlayerResponse{}
	mi := &file_proto_lobby_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickPlayerResponse) ProtoMessage() {}

func (x *KickPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickPlayerResponse.ProtoReflect.Descriptor instead.
func (*KickPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{20}
}

func (x *KickPlayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KickPlayerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamLobbyUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLobbyUpdatesRequest) Reset() {
	*x = StreamLobbyUpdatesRequest{}
	mi := &file_proto_lobby_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLobbyUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLobbyUpdatesRequest) ProtoMessage() {}

func (x *StreamLobbyUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLobbyUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamLobbyUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{21}
}

type LobbyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *LobbyState            `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	UpdateType    LobbyUpdateType        `protobuf:"varint,2,opt,name=update_type,json=updateType,proto3,enum=lobby.LobbyUpdateType" json:"update_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyUpdate) Reset() {
	*x = LobbyUpdate{}
	mi := &file_proto_lobby_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyUpdate) ProtoMessage() {}

func (x *LobbyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyUpdate.ProtoReflect.Descriptor instead.
func (*LobbyUpdate) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{22}
}

func (x *LobbyUpdate) GetState() *LobbyState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *LobbyUpdate) GetUpdateType() LobbyUpdateType {
	if x != nil {
		return x.UpdateType
	}
	return LobbyUpdateType_UPDATE_TYPE_UNKNOWN
}

func (x *LobbyUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetBotStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBotStatusRequest) Reset() {
	*x = GetBotStatusRequest{}
	mi := &file_proto_lobby_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBotStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBotStatusRequest) ProtoMessage() {}

func (x *GetBotStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBotStatusRequest.ProtoReflect.Descriptor instead.
func (*GetBotStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{23}
}

type BotStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connected     bool                   `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	SteamUsername string                 `protobuf:"bytes,3,opt,name=steam_username,json=steamUsername,proto3" json:"steam_username,omitempty"`
	SteamId       uint64                 `protobuf:"varint,4,opt,name=steam_id,json=steamId,proto3" json:"steam_id,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	InLobby       bool                   `protobuf:"varint,6,opt,name=in_lobby,json=inLobby,proto3" json:"in_lobby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotStatus) Reset() {
	*x = BotStatus{}
	mi := &file_proto_lobby_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotStatus) ProtoMessage() {}

func (x *BotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lobby_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotStatus.ProtoReflect.Descriptor instead.
func (*BotStatus) Descriptor() ([]byte, []int) {
	return file_proto_lobby_proto_rawDescGZIP(), []int{24}
}

func (x *BotStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *BotStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *BotStatus) GetSteamUsername() string {
	if x != nil {
		return x.SteamUsername
	}
	return ""
}

func (x *BotStatus) GetSteamId() uint64 {
	if x != nil {
		return x.SteamId
	}
	return 0
}

func (x *BotStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *BotStatus) GetInLobby() bool {
	if x != nil {
		return x.InLobby
	}
	return false
}

var File_proto_lobby_proto protoreflect.FileDescriptor

const file_proto_lobby_proto_rawDesc = "" +
	"\n" +
	"\x11proto/lobby.proto\x12\x05lobby\"\xfe\x01\n" +
	"\x12CreateLobbyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rserver_region\x18\x03 \x01(\rR\fserverRegion\x12\x1b\n" +
	"\tgame_mode\x18\x04 \x01(\rR\bgameMode\x12!\n" +
	"\fallow_cheats\x18\x05 \x01(\bR\vallowCheats\x12)\n" +
	"\x10allow_spectators\x18\x06 \x01(\bR\x0fallowSpectators\x12(\n" +
	"\x10invite_steam_ids\x18\a \x03(\x04R\x0einviteSteamIds\"|\n" +
	"\x13CreateLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\blobby_id\x18\x03 \x01(\x04R\alobbyId\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"3\n" +
	"\x14InvitePlayersRequest\x12\x1b\n" +
	"\tsteam_ids\x18\x01 \x03(\x04R\bsteamIds\"\xe1\x01\n" +
	"\x15InvitePlayersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12V\n" +
	"\x0einvite_results\x18\x03 \x03(\v2/.lobby.InvitePlayersResponse.InviteResultsEntryR\rinviteResults\x1a@\n" +
	"\x12InviteResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x15ConfigureLobbyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rserver_region\x18\x03 \x01(\rR\fserverRegion\x12\x1b\n" +
	"\tgame_mode\x18\x04 \x01(\rR\bgameMode\x12!\n" +
	"\fallow_cheats\x18\x05 \x01(\bR\vallowCheats\x12)\n" +
	"\x10allow_spectators\x18\x06 \x01(\bR\x0fallowSpectators\"H\n" +
	"\x16ConfigureLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12LaunchLobbyRequest\"`\n" +
	"\x13LaunchLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\x04R\amatchId\"\x13\n" +
	"\x11LeaveLobbyRequest\"D\n" +
	"\x12LeaveLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x15\n" +
	"\x13DestroyLobbyRequest\"F\n" +
	"\x14DestroyLobbyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x16\n" +
	"\x14GetLobbyStateRequest\"\xed\x02\n" +
	"\n" +
	"LobbyState\x12\x19\n" +
	"\bin_lobby\x18\x01 \x01(\bR\ainLobby\x12\x19\n" +
	"\blobby_id\x18\x02 \x01(\x04R\alobbyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12*\n" +
	"\x06status\x18\x05 \x01(\x0e2\x12.lobby.LobbyStatusR\x06status\x12#\n" +
	"\rserver_region\x18\x06 \x01(\rR\fserverRegion\x12\x1b\n" +
	"\tgame_mode\x18\a \x01(\rR\bgameMode\x12\x19\n" +
	"\bmatch_id\x18\b \x01(\x04R\amatchId\x12,\n" +
	"\amembers\x18\t \x03(\v2\x12.lobby.LobbyMemberR\amembers\x12#\n" +
	"\rradiant_count\x18\n" +
	" \x01(\x05R\fradiantCount\x12\x1d\n" +
	"\n" +
	"dire_count\x18\v \x01(\x05R\tdireCount\"\xc9\x01\n" +
	"\vLobbyMember\x12\x19\n" +
	"\bsteam_id\x18\x01 \x01(\x04R\asteamId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\rR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12$\n" +
	"\x04team\x18\x04 \x01(\x0e2\x10.lobby.LobbyTeamR\x04team\x12\x12\n" +
	"\x04slot\x18\x05 \x01(\rR\x04slot\x12\x19\n" +
	"\bis_ready\x18\x06 \x01(\bR\aisReady\x12\x17\n" +
	"\ais_host\x18\a \x01(\bR\x06isHost\"\x15\n" +
	"\x13ShuffleTeamsRequest\"F\n" +
	"\x14ShuffleTeamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10FlipTeamsRequest\"C\n" +
	"\x11FlipTeamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x11KickPlayerRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\rR\taccountId\"D\n" +
	"\x12KickPlayerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1b\n" +
	"\x19StreamLobbyUpdatesRequest\"\x8d\x01\n" +
	"\vLobbyUpdate\x12'\n" +
	"\x05state\x18\x01 \x01(\v2\x11.lobby.LobbyStateR\x05state\x127\n" +
	"\vupdate_type\x18\x02 \x01(\x0e2\x16.lobby.LobbyUpdateTypeR\n" +
	"updateType\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x15\n" +
	"\x13GetBotStatusRequest\"\xc3\x01\n" +
	"\tBotStatus\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12%\n" +
	"\x0esteam_username\x18\x03 \x01(\tR\rsteamUsername\x12\x19\n" +
	"\bsteam_id\x18\x04 \x01(\x04R\asteamId\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12\x19\n" +
	"\bin_lobby\x18\x06 \x01(\bR\ainLobby*\xa9\x01\n" +
	"\vLobbyStatus\x12\x18\n" +
	"\x14LOBBY_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14LOBBY_STATUS_CREATED\x10\x01\x12\x18\n" +
	"\x14LOBBY_STATUS_WAITING\x10\x02\x12\x16\n" +
	"\x12LOBBY_STATUS_READY\x10\x03\x12\x18\n" +
	"\x14LOBBY_STATUS_IN_GAME\x10\x04\x12\x1a\n" +
	"\x16LOBBY_STATUS_POST_GAME\x10\x05*k\n" +
	"\tLobbyTeam\x12\x13\n" +
	"\x0fTEAM_UNASSIGNED\x10\x00\x12\x10\n" +
	"\fTEAM_RADIANT\x10\x01\x12\r\n" +
	"\tTEAM_DIRE\x10\x02\x12\x12\n" +
	"\x0eTEAM_SPECTATOR\x10\x03\x12\x14\n" +
	"\x10TEAM_BROADCASTER\x10\x04*\x8c\x02\n" +
	"\x0fLobbyUpdateType\x12\x17\n" +
	"\x13UPDATE_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13UPDATE_TYPE_CREATED\x10\x01\x12\x1e\n" +
	"\x1aUPDATE_TYPE_CONFIG_CHANGED\x10\x02\x12\x1d\n" +
	"\x19UPDATE_TYPE_PLAYER_JOINED\x10\x03\x12\x1b\n" +
	"\x17UPDATE_TYPE_PLAYER_LEFT\x10\x04\x12\x1c\n" +
	"\x18UPDATE_TYPE_TEAM_CHANGED\x10\x05\x12\x18\n" +
	"\x14UPDATE_TYPE_LAUNCHED\x10\x06\x12\x18\n" +
	"\x14UPDATE_TYPE_FINISHED\x10\a\x12\x19\n" +
	"\x15UPDATE_TYPE_DESTROYED\x10\b*\xce\x02\n" +
	"\fServerRegion\x12\x16\n" +
	"\x12REGION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eREGION_US_WEST\x10\x01\x12\x12\n" +
	"\x0eREGION_US_EAST\x10\x02\x12\x11\n" +
	"\rREGION_EUROPE\x10\x03\x12\x10\n" +
	"\fREGION_KOREA\x10\x04\x12\x14\n" +
	"\x10REGION_SINGAPORE\x10\x05\x12\x10\n" +
	"\fREGION_DUBAI\x10\x06\x12\x14\n" +
	"\x10REGION_AUSTRALIA\x10\a\x12\x14\n" +
	"\x10REGION_STOCKHOLM\x10\b\x12\x12\n" +
	"\x0eREGION_AUSTRIA\x10\t\x12\x11\n" +
	"\rREGION_BRAZIL\x10\n" +
	"\x12\x17\n" +
	"\x13REGION_SOUTH_AFRICA\x10\v\x12\x10\n" +
	"\fREGION_CHILE\x10\x0e\x12\x0f\n" +
	"\vREGION_PERU\x10\x0f\x12\x10\n" +
	"\fREGION_INDIA\x10\x10\x12\x10\n" +
	"\fREGION_JAPAN\x10\x13*\xa8\x01\n" +
	"\bGameMode\x12\x15\n" +
	"\x11GAME_MODE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12GAME_MODE_ALL_PICK\x10\x01\x12\x1b\n" +
	"\x17GAME_MODE_CAPTAINS_MODE\x10\x02\x12\x1a\n" +
	"\x16GAME_MODE_RANDOM_DRAFT\x10\x03\x12\x1a\n" +
	"\x16GAME_MODE_SINGLE_DRAFT\x10\x04\x12\x18\n" +
	"\x14GAME_MODE_ALL_RANDOM\x10\x052\xda\x06\n" +
	"\fLobbyService\x12D\n" +
	"\vCreateLobby\x12\x19.lobby.CreateLobbyRequest\x1a\x1a.lobby.CreateLobbyResponse\x12J\n" +
	"\rInvitePlayers\x12\x1b.lobby.InvitePlayersRequest\x1a\x1c.lobby.InvitePlayersResponse\x12M\n" +
	"\x0eConfigureLobby\x12\x1c.lobby.ConfigureLobbyRequest\x1a\x1d.lobby.ConfigureLobbyResponse\x12D\n" +
	"\vLaunchLobby\x12\x19.lobby.LaunchLobbyRequest\x1a\x1a.lobby.LaunchLobbyResponse\x12A\n" +
	"\n" +
	"LeaveLobby\x12\x18.lobby.LeaveLobbyRequest\x1a\x19.lobby.LeaveLobbyResponse\x12G\n" +
	"\fDestroyLobby\x12\x1a.lobby.DestroyLobbyRequest\x1a\x1b.lobby.DestroyLobbyResponse\x12?\n" +
	"\rGetLobbyState\x12\x1b.lobby.GetLobbyStateRequest\x1a\x11.lobby.LobbyState\x12G\n" +
	"\fShuffleTeams\x12\x1a.lobby.ShuffleTeamsRequest\x1a\x1b.lobby.ShuffleTeamsResponse\x12>\n" +
	"\tFlipTeams\x12\x17.lobby.FlipTeamsRequest\x1a\x18.lobby.FlipTeamsResponse\x12A\n" +
	"\n" +
	"KickPlayer\x12\x18.lobby.KickPlayerRequest\x1a\x19.lobby.KickPlayerResponse\x12L\n" +
	"\x12StreamLobbyUpdates\x12 .lobby.StreamLobbyUpdatesRequest\x1a\x12.lobby.LobbyUpdate0\x01\x12<\n" +
	"\fGetBotStatus\x12\x1a.lobby.GetBotStatusRequest\x1a\x10.lobby.BotStatusB&Z$github.com/dota-league/dota-gc/protob\x06proto3"

var (
	file_proto_lobby_proto_rawDescOnce sync.Once
	file_proto_lobby_proto_rawDescData []byte
)

func file_proto_lobby_proto_rawDescGZIP() []byte {
	file_proto_lobby_proto_rawDescOnce.Do(func() {
		file_proto_lobby_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lobby_proto_rawDesc), len(file_proto_lobby_proto_rawDesc)))
	})
	return file_proto_lobby_proto_rawDescData
}

var file_proto_lobby_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_lobby_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_lobby_proto_goTypes = []any{
	(LobbyStatus)(0),                  // 0: lobby.LobbyStatus
	(LobbyTeam)(0),                    // 1: lobby.LobbyTeam
	(LobbyUpdateType)(0),              // 2: lobby.LobbyUpdateType
	(ServerRegion)(0),                 // 3: lobby.ServerRegion
	(GameMode)(0),                     // 4: lobby.GameMode
	(*CreateLobbyRequest)(nil),        // 5: lobby.CreateLobbyRequest
	(*CreateLobbyResponse)(nil),       // 6: lobby.CreateLobbyResponse
	(*InvitePlayersRequest)(nil),      // 7: lobby.InvitePlayersRequest
	(*InvitePlayersResponse)(nil),     // 8: lobby.InvitePlayersResponse
	(*ConfigureLobbyRequest)(nil),     // 9: lobby.ConfigureLobbyRequest
	(*ConfigureLobbyResponse)(nil),    // 10: lobby.ConfigureLobbyResponse
	(*LaunchLobbyRequest)(nil),        // 11: lobby.LaunchLobbyRequest
	(*LaunchLobbyResponse)(nil),       // 12: lobby.LaunchLobbyResponse
	(*LeaveLobbyRequest)(nil),         // 13: lobby.LeaveLobbyRequest
	(*LeaveLobbyResponse)(nil),        // 14: lobby.LeaveLobbyResponse
	(*DestroyLobbyRequest)(nil),       // 15: lobby.DestroyLobbyRequest
	(*DestroyLobbyResponse)(nil),      // 16: lobby.DestroyLobbyResponse
	(*GetLobbyStateRequest)(nil),      // 17: lobby.GetLobbyStateRequest
	(*LobbyState)(nil),                // 18: lobby.LobbyState
	(*LobbyMember)(nil),               // 19: lobby.LobbyMember
	(*ShuffleTeamsRequest)(nil),       // 20: lobby.ShuffleTeamsRequest
	(*ShuffleTeamsResponse)(nil),      // 21: lobby.ShuffleTeamsResponse
	(*FlipTeamsRequest)(nil),          // 22: lobby.FlipTeamsRequest
	(*FlipTeamsResponse)(nil),         // 23: lobby.FlipTeamsResponse
	(*KickPlayerRequest)(nil),         // 24: lobby.KickPlayerRequest
	(*KickPlayerResponse)(nil),        // 25: lobby.KickPlayerResponse
	(*StreamLobbyUpdatesRequest)(nil), // 26: lobby.StreamLobbyUpdatesRequest
	(*LobbyUpdate)(nil),               // 27: lobby.LobbyUpdate
	(*GetBotStatusRequest)(nil),       // 28: lobby.GetBotStatusRequest
	(*BotStatus)(nil),                 // 29: lobby.BotStatus
	nil,                               // 30: lobby.InvitePlayersResponse.InviteResultsEntry
}
var file_proto_lobby_proto_depIdxs = []int32{
	30, // 0: lobby.InvitePlayersResponse.invite_results:type_name -> lobby.InvitePlayersResponse.InviteResultsEntry
	0,  // 1: lobby.LobbyState.status:type_name -> lobby.LobbyStatus
	19, // 2: lobby.LobbyState.members:type_name -> lobby.LobbyMember
	1,  // 3: lobby.LobbyMember.team:type_name -> lobby.LobbyTeam
	18, // 4: lobby.LobbyUpdate.state:type_name -> lobby.LobbyState
	2,  // 5: lobby.LobbyUpdate.update_type:type_name -> lobby.LobbyUpdateType
	5,  // 6: lobby.LobbyService.CreateLobby:input_type -> lobby.CreateLobbyRequest
	7,  // 7: lobby.LobbyService.InvitePlayers:input_type -> lobby.InvitePlayersRequest
	9,  // 8: lobby.LobbyService.ConfigureLobby:input_type -> lobby.ConfigureLobbyRequest
	11, // 9: lobby.LobbyService.LaunchLobby:input_type -> lobby.LaunchLobbyRequest
	13, // 10: lobby.LobbyService.LeaveLobby:input_type -> lobby.LeaveLobbyRequest
	15, // 11: lobby.LobbyService.DestroyLobby:input_type -> lobby.DestroyLobbyRequest
	17, // 12: lobby.LobbyService.GetLobbyState:input_type -> lobby.GetLobbyStateRequest
	20, // 13: lobby.LobbyService.ShuffleTeams:input_type -> lobby.ShuffleTeamsRequest
	22, // 14: lobby.LobbyService.FlipTeams:input_type -> lobby.FlipTeamsRequest
	24, // 15: lobby.LobbyService.KickPlayer:input_type -> lobby.KickPlayerRequest
	26, // 16: lobby.LobbyService.StreamLobbyUpdates:input_type -> lobby.StreamLobbyUpdatesRequest
	28, // 17: lobby.LobbyService.GetBotStatus:input_type -> lobby.GetBotStatusRequest
	6,  // 18: lobby.LobbyService.CreateLobby:output_type -> lobby.CreateLobbyResponse
	8,  // 19: lobby.LobbyService.InvitePlayers:output_type -> lobby.InvitePlayersResponse
	10, // 20: lobby.LobbyService.ConfigureLobby:output_type -> lobby.ConfigureLobbyResponse
	12, // 21: lobby.LobbyService.LaunchLobby:output_type -> lobby.LaunchLobbyResponse
	14, // 22: lobby.LobbyService.LeaveLobby:output_type -> lobby.LeaveLobbyResponse
	16, // 23: lobby.LobbyService.DestroyLobby:output_type -> lobby.DestroyLobbyResponse
	18, // 24: lobby.LobbyService.GetLobbyState:output_type -> lobby.LobbyState
	21, // 25: lobby.LobbyService.ShuffleTeams:output_type -> lobby.ShuffleTeamsResponse
	23, // 26: lobby.LobbyService.FlipTeams:output_type -> lobby.FlipTeamsResponse
	25, // 27: lobby.LobbyService.KickPlayer:output_type -> lobby.KickPlayerResponse
	27, // 28: lobby.LobbyService.StreamLobbyUpdates:output_type -> lobby.LobbyUpdate
	29, // 29: lobby.LobbyService.GetBotStatus:output_type -> lobby.BotStatus
	18, // [18:30] is the sub-list for method output_type
	6,  // [6:18] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_lobby_proto_init() }
func file_proto_lobby_proto_init() {
	if File_proto_lobby_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lobby_proto_rawDesc), len(file_proto_lobby_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lobby_proto_goTypes,
		DependencyIndexes: file_proto_lobby_proto_depIdxs,
		EnumInfos:         file_proto_lobby_proto_enumTypes,
		MessageInfos:      file_proto_lobby_proto_msgTypes,
	}.Build()
	File_proto_lobby_proto = out.File
	file_proto_lobby_proto_goTypes = nil
	file_proto_lobby_proto_depIdxs = nil
}
